version: 2

references:
  container_config: &container_config
    docker:
      - image: google/cloud-sdk
    working_directory: ~/alpine-orangesys-influxdb

jobs:
  build_container:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/alpine-orangeapi.tar
      - run:
          name: Install docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp/ -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build alpine-orangesys-influxdb container images
          command: |
            set +o pipefail
            ./scripts/create-container.sh
      - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
          - /caches/alpine-orangeapi.tar

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_container